title = "STACKL"
baseURL = "https://stackl.io/"
languageCode = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
googleAnalytics = ""

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "tango"
pygmentsGuessSyntax = true

# Don't try and render the code snippets as html pages
# the are loaded via shortcode helpers.
ignorefiles = [ "/docs/v.*/code/.*" ]

[params]
description = "An open source, end-to-end application orchestration platform"
tagline = ""
algolia_api_key = ""

[params.social]
twitter = "stacklio"
slack = "https://stacklio.slack.com/"
github = "https://github.com/stacklio"

[params.logos]
sidebar = "/img/logos/opa-horizontal-color.png"
navbar = "/img/logos/opa-icon-white.png"

[menu]

[[menu.social]]
name = "Twitter"
url = "https://twitter.com/stacklio"
weight = 2

[[menu.social]]
name = "Slack"
url = "https://stacklio.slack.com/"
weight = 3

[[menu.social]]
name = "GitHub"
url = "https://github.com/stacklio"
weight = 4

[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"

[outputs]
home = ["HTML", "REDIRECTS"]
